apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        env:
          - name: POSTGRES_USER
            value: abhishek
          - name: POSTGRES_PASSWORD
            value: abhishek
          - name: POSTGRES_DB
            value: abhishek
        ports:
        - containerPort: 5432
        volumeMounts:  # Add this section
          - name: postgres-data
            mountPath: /var/lib/postgresql/data  # The path inside the container
      volumes:  # Add this section
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
